# Generated by Django 5.2.10 on 2026-02-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel_integration", "0007_add_enrollment_events_processing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enterprisewebhookconfiguration",
            old_name="enrollment_events_processing",
            new_name="enable_enrollment_events_processing",
        ),
        migrations.AlterField(
            model_name="enterprisewebhookconfiguration",
            name="region",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("EU", "European Union"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                help_text="Geographic region this webhook URL is for",
                max_length=10,
            ),
        ),
    ]
