# Generated by Django 5.2.10 on 2026-02-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "channel_integration",
            "0008_rename_enrollment_events_processing_enterprisewebhookconfiguration_enable_enrollment_events_processi",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprisewebhookconfiguration",
            name="webhook_auth_token",
        ),
        migrations.AddField(
            model_name="enterprisewebhookconfiguration",
            name="webhook_token_url",
            field=models.URLField(
                blank=True,
                help_text="HTTPS endpoint to get bearer token (10hr until expiration) to access webhooks",
                max_length=500,
                null=True,
            ),
        ),
    ]
