# Generated by Django 5.2.15 on 2026-09-18 12:02

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sap_success_factors_channel",
            "0006_sapsuccessfactorsenterprisecustomerconfiguration_transmit_course_hours",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("legacy", "Legacy (SAP OAuth IdP API)"),
                    (
                        "modern_saml_bearer",
                        "Modern (self-signed SAML bearer assertion)",
                    ),
                ],
                default="legacy",
                help_text="How access tokens are obtained for this customer. 'Legacy' asks SAP's OAuth IdP API to mint the SAML assertion for us; 'Modern' signs the assertion ourselves with the configured private key. Existing customers stay on 'Legacy' until they have been migrated.",
                max_length=32,
                verbose_name="SAP Auth Type",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="decrypted_private_key",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="The PEM-encoded private key used to sign the SAML bearer assertion sent to this customer's token endpoint. Only used when the auth type is 'Modern'. It will be encrypted when stored in the database.",
                null=True,
                verbose_name="Encrypted Private Key",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="oauth_token_api_path",
            field=models.CharField(
                blank=True,
                default="/oauth/token",
                help_text="Tenant-specific path, relative to the SAP base URL, of the endpoint that exchanges a SAML bearer assertion for an access token.",
                max_length=255,
                verbose_name="OAuth Token API Path",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="saml_assertion_api_path",
            field=models.CharField(
                blank=True,
                default="/oauth/idp",
                help_text="Tenant-specific path, relative to the SAP base URL, of the endpoint that issues the SAML assertion exchanged for an access token. Overrides the global OAuth API path.",
                max_length=255,
                verbose_name="SAML Assertion API Path",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="saml_assertion_audience",
            field=models.CharField(
                blank=True,
                default="www.successfactors.com",
                help_text="Value of the Audience restriction in the SAML bearer assertion sent to this customer's token endpoint. Only used when the auth type is 'Modern'.",
                max_length=255,
                verbose_name="SAML Assertion Audience",
            ),
        ),
    ]
