# Generated by Django 5.2.12 on 2026-08-28 06:54

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cornerstone_channel",
            "0003_alter_cornerstoneenterprisecustomerconfiguration_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cornerstoneenterprisecustomerconfiguration",
            name="completion_scope",
            field=models.CharField(
                blank=True,
                default="transcript:update learningassignment:read learningassignment:update",
                help_text="The OAuth scope requested when minting an access token for pushing completions, covering both the Transcript API and the Learning Assignments API.",
                max_length=255,
                verbose_name="OAuth Completion Scope",
            ),
        ),
        migrations.AddField(
            model_name="cornerstoneenterprisecustomerconfiguration",
            name="decrypted_client_id",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="The OAuth Client ID (encrypted at rest) that the enterprise customer gave edX for requesting access tokens used to push course completions. If this and the client secret are both configured, completions are authenticated via OAuth rather than the learner's launch-time session token.",
                max_length=255,
                null=True,
                verbose_name="Encrypted OAuth Client ID",
            ),
        ),
        migrations.AddField(
            model_name="cornerstoneenterprisecustomerconfiguration",
            name="decrypted_client_secret",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="The encrypted OAuth Client Secret provided to edX by the enterprise customer, used to obtain access tokens for pushing course completions.",
                max_length=255,
                null=True,
                verbose_name="Encrypted OAuth Client Secret",
            ),
        ),
        migrations.AddField(
            model_name="cornerstoneenterprisecustomerconfiguration",
            name="learning_assignments_api_path",
            field=models.CharField(
                blank=True,
                default="/services/api/v1/LearningAssignments",
                help_text="The API path used to look up and update a learner's in-progress assignment through Cornerstone's Learning Assignments API, used once this customer is authenticated with OAuth.",
                max_length=255,
                verbose_name="Learning Assignments API Path",
            ),
        ),
        migrations.AddField(
            model_name="cornerstoneenterprisecustomerconfiguration",
            name="transcript_complete_api_path",
            field=models.CharField(
                blank=True,
                default="/services/api/v1/transcripts/complete",
                help_text="The API path used to mark a learner's transcript complete through Cornerstone's Transcript API, used once this customer is authenticated with OAuth.",
                max_length=255,
                verbose_name="Transcript Complete API Path",
            ),
        ),
    ]
