# Generated by Django 5.2.15 on 2026-08-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sap_success_factors_channel",
            "0005_rename_sap_success_enterpr_8151d6_idx_sap_success_factors_audit_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="transmit_course_hours",
            field=models.BooleanField(
                default=False,
                help_text="Include totalHours/creditHours in the transmitted course catalog (content metadata) payload. This is independent of 'Transmit Total Hours', which only affects completion data -- some SAP endpoints reject unrecognized fields, so only enable this for customers who have explicitly requested it.",
                verbose_name="Transmit Course Hours (Catalog)",
            ),
        ),
    ]
