# Generated by Django 5.2.10 on 2026-02-25 02:44

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canvas_channel", "0004_mariadb_uuid_conversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canvasenterprisecustomerconfiguration",
            name="decrypted_client_secret",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="The encrypted API Client Secret provided to edX by the enterprise customer to be used to make API calls to Canvas on behalf of the customer. It will be encrypted when stored in the database.",
                max_length=255,
                null=True,
                verbose_name="Encrypted API Client Secret",
            ),
        ),
    ]
