# Generated by Django 5.2.10 on 2026-02-25 00:53

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel_integration", "0007_add_enrollment_events_processing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enterprisewebhookconfiguration",
            old_name="enrollment_events_processing",
            new_name="enable_enrollment_events_processing",
        ),
        migrations.AddField(
            model_name="enterprisewebhookconfiguration",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="Percipio OAuth2 client ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprisewebhookconfiguration",
            name="decrypted_client_secret",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="The encrypted API Client Secret provided to edX by the Percipio team. It will be encrypted when stored in the database.",
                max_length=255,
                null=True,
                verbose_name="Encrypted API Client Secret",
            ),
        ),
        migrations.AlterField(
            model_name="enterprisewebhookconfiguration",
            name="region",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("EU", "European Union"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                help_text="Geographic region this webhook URL is for",
                max_length=10,
            ),
        ),
    ]
