# Generated by Django 5.2.9 on 2026-08-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_integration', '0011_create_tpa_org_allowlist_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaorgallowlist',
            name='enterprise_group_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Budget-type EnterpriseGroup that learners asserting this org should be placed in. Null means this org is allowlisted for login but has no budget mapped yet.', null=True),
        ),
    ]
