# Generated by Django 5.2.10 on 2026-02-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi_channel', '0003_alter_xapilearnerdatatransmissionaudit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
    ]
