# Generated by Django migration
"""
ENT-12011: Increase the default transmission_chunk_size for Blackboard from 1 to 10.

This change prevents 429 (Too Many Requests) rate limiting errors on Blackboard
developer accounts by batching data into larger, fewer API payloads instead of
sending one request per item.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard_channel', '0004_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackboardenterprisecustomerconfiguration',
            name='transmission_chunk_size',
            field=models.IntegerField(
                default=10,
                help_text=(
                    'The maximum number of data items to transmit to the integrated channel '
                    'with each request.'
                ),
            ),
        ),
    ]
